name: Windows EXE (Qt 6, MSVC 2022)

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем Qt 6.x для MSVC 2022 (без modules:)
      - name: Install Qt (Windows, MSVC 2022)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.1          # можно 'latest'
          host: windows
          arch: win64_msvc2022_64
          cache: true

      # (необязательно) Диагностика: покажем, что Qt найден и где он лежит
      - name: Show Qt env
        run: |
          echo Qt6_DIR=%Qt6_DIR%
          where qmake
          qmake -v

      # Конфигурация CMake под MSVC 2022 + прокидываем CMAKE_PREFIX_PATH из %Qt6_DIR%
      - name: Configure (CMake, MSVC 2022)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%Qt6_DIR%

      - name: Build
        run: cmake --build build --config Release

      # Разворачивание Qt DLL рядом с exe
      - name: Deploy Qt DLLs
        run: |
          cd build\Release
          windeployqt Mandelbrot.exe
          if (!(Test-Path dist)) { New-Item -ItemType Directory dist | Out-Null }
          Copy-Item Mandelbrot.exe dist\
          Copy-Item *.dll -Destination dist\ -ErrorAction SilentlyContinue
          cd ..\..

      - name: Zip artifact
        run: powershell Compress-Archive -Path build\Release\dist\* -DestinationPath Mandelbrot-win64.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mandelbrot-win64
          path: Mandelbrot-win64.zip
